language: generic
dist: xenial
sudo: false
env:
  - PERL_VERSION=5.8.1
  - PERL_VERSION=5.10.1
  - PERL_VERSION=5.16.3
  - PERL_VERSION=5.28.1
install:
  - curl -fsSL --compressed https://git.io/cpm -o cpm
  - curl -fsSL https://github.com/skaji/cpm-test/releases/download/0.01/ubuntu-16.04-perl-$PERL_VERSION.tar.xz | tar xJf - -C /tmp
  - export PATH=/tmp/perl-$PERL_VERSION/bin:$PATH
script:
  - perl -V
  - perl cpm -V
  - make test
